### ISSUE TITLE
org indentation not right

### ISSUE THREAD

**Issue by jdtsmith** [positron-solutions/transient-showcase#22]
org-indent adds level based indentation automatically.  You seem to have pre-indented things "by hand".  This is OK but leads to double-indentation, and breaks things like `org-modern-indent`:

<img width="201" alt="image" src="https://github.com/positron-solutions/transient-showcase/assets/93749/07b65a88-6509-43dc-8e5c-d447de0a8f89">

**Comment by psionic-k** [comment]
I made this a while ago and also abandoned indentation.  PR welcome.

**Comment by jdtsmith** [comment]
See #23.

**Comment by psionic-k** [comment]
I manually pushed your changes and did a lot of edits on top.  Re-open if there's an issue with the result.

I ended up making a surprising number of edits.

Anyway the combination of visual-line-mode, visual-fill-column, and adaptive-wrap are perfect

**Comment by jdtsmith** [comment]
If you use `org-indent`, adaptive wrapping is "built in".   It's looking good:

<img width="638" alt="image" src="https://github.com/positron-solutions/transient-showcase/assets/93749/4b2296b1-1e60-41e2-a6e6-f4afabd64b96">

**Comment by jdtsmith** [comment]
BTW in the EIEIO section I noticed uses of `(plist-get (symbol-plist 'magit-dispatch) 'transient--prefix)`, which can be shortened to `(get 'magit-dispatch 'transient--prefix)`.

**Comment by psionic-k** [comment]
That's hot.  Thanks.

**Comment by jdtsmith** [comment]
I always thought it was funny that the very primitive and basic-sounding `get` and `put` access a type of symbol metadata most elisp programmers don't get around to using for a long time!

**Comment by psionic-k** [comment]
I didn't even mention that in the Elisp Idiosyncrasies video I did, and I touched on symbol-plists:  https://youtu.be/D8391afYiRs
