### ISSUE TITLE
passing data/arguments to transients/prefixes

### ISSUE THREAD

**Issue by mooseyboots** [positron-solutions/transient-showcase#29]
i've been studying the showcase for a while now (thanks!), and i have a few nagging questions still.

i'm trying to make a transient menu that works a bit like html forms: set a bunch of user options, then POST or PATCH the result to a REST API.

one question i have is, is it possible to somehow hand some arguments/(JSON) data to a transient?

reasons to do so in my case are, more simply, to provide default values, and more trickily, to dynamically generate all menu options based on the data. (GET the data, generate the transient, user then sets the options, and POSTS the updated data.)

the only way so far i can see is to rely on global variables, which my package mostly eschews for the sake of buffer-local ones. but in a transient context we are no longer in the buffer with the data.

then i came up with an awful hack, something like:

```lisp
(lambda ()
   (with-current-buffer (car (buffer-list))
      (get-data-from previous-buffer)))      
```

but surely that's not the way to go about it.

any pointers appreciated!

**Comment by martianhi** [comment]
`transient--original-buffer` does the trick!

docs, possibly old, mention `transient--source-buffer` but now its the above.

**Comment by psionic-k** [comment]
Also see `transient--shadowed-buffer`.  I'm doing an example on buffer locals with transient right now.

Duplicates #25.  Will close when I get the example up.

**Comment by psionic-k** [comment]
It seems all of these approaches are valid.  Can you provide an example of the situation that was breaking?  I was unable to ever see an incorrect value of `current-buffer` in the latest version of transient 0.7.7.  The current buffer always pointed to the one that invoked the transient in every situation I tested.

Feel free to re-open if this still needs some attention.
