### ISSUE TITLE
a problem trying the samples using use-package, vc method

### ISSUE THREAD

**Issue by jave** [positron-solutions/transient-showcase#31]
(package-vc-install
 '(transient-showcase
   :url "https://github.com/positron-solutions/transient-showcase.git"))
(require 'transient-showcase) ; now you can access the commands

and i get an error:

In toplevel form:
transient-showcase.el:188:2: Error: Invalid transient--parse-child spec: nil

**Comment by psionic-k** [comment]
Reproduced.  Updated to work with latest version of transient.  Thanks :+1:
