### ISSUE TITLE
null argument despite "non-null" name.

### ISSUE THREAD

**Issue by progfolio** [positron-solutions/transient-showcase#6]
# Managing State > "sb" a bunch of infixes

For the --non-null option, if the user accepts an empty prompt the option is null.

To reproduce:

1. `M-x ts-show case`
2. `s` `b`
3. `-` `n` `RET` 
4. `s` to show arguments

The output is:

```
prefix-arg: nil
prefix's scope value: nil
transient-args: nil
```

**Comment by psionic-k** [comment]
https://github.com/magit/transient/pull/228  Upstream change is necessary to fully resolve
