### ISSUE TITLE
Access args within :description lambda

### ISSUE THREAD

**Issue by jdtsmith** [positron-solutions/transient-showcase#9]
Thanks for these wonderful examples.  I keep the org file pulled up and consult-line through when confused by something in transient.  

One thing I'm wondering: you mention the ambiguity between times `transient-current-command` and `transient--prefix` may be required to introspect the current state of the transient's various values.  I'm interested in gathering the infix arguments in a lambda function attached to the `:description` of a given suffix.  I'd like to do this to provide the user a _preview_ of the action they are about to take (in my case, creating a special buffer).  Unfortunately, I haven't found a way to do that.  `transient-current-command` is nil and `transient--prefix`'s value does not change in a `:description` lambda as you update infixes.  `transient-args` on the hard-coded symbol of my prefix gives a fixed set of initial values only; i.e. it does not update as the user alters infixes. 

Thanks again.

**Comment by jdtsmith** [comment]
Update: I figured out a method. The issue is that `transient-current-suffixes` (like `transient-current-prefix`) only gets set (by `transient--export`) as a suffix is called.  But similar to `transient--prefix`, there is the internal state `transient--suffixes`.  

```elisp
(let ((args (cl-mapcan #'transient--get-wrapped-value ; can't yet use transient-args!
			      (transient--flatten-suffixes transient--suffixes))))
                 (transient-arg-value "--somekey" args)
                 ...
```

**Comment by psionic-k** [comment]
> ambiguity between times

IIRC `transient--prefix` does contain the upcoming transient object during layout.  I found this line pointing to a usage of `transient--prefix` within a lambda for description:

> [:description (lambda () (format "Scope: %s" (oref transient--prefix scope)))

This is from the `tsc-scope` example.  You can use the object to get the command symbol with `(oref transient--prefix command)`.

However, descriptions for suffixes only happens once per layout.  Groups are updated on every key.  You might use this as a workaround for now.  There's some errata from the document around Dynamic Descriptions (just updated)

https://github.com/positron-solutions/transient-showcase/commit/d28080d63f82b8c29f2e1ee9774172d1a33325c1

**Comment by jdtsmith** [comment]
Thanks.  I admit I don't quite know what `scope` is for.  

I'm confused about your update text though; my suffix description indeed updates on each key press.  Seems to be working fine, only issue IMO is the use of "hidden" `--` vars and functions, but it seems to be a recommended approach.  Here's a test example:

```elisp
((defun my/ret-action (args)
  (interactive (list (transient-args transient-current-command)))
  (message "Got args: %S" args))

(transient-define-prefix test-suffix-description-update ()
  ["Some options:"
   ("-c" "command" "--command=" :always-read t)
   ("-f" "frobnicate" "--frobnicate")]
  ["Actions:"
   ( "RET" my/ret-action
     :description
     (lambda ()
       (let* ((transient-current-command (oref transient--prefix command))
              (transient-current-suffixes transient--suffixes)
              (args (transient-args transient-current-command)))
	 (format "Run %s with %s"
                 (if-let (cmd (transient-arg-value "--command=" args))
                     (propertize cmd 'face 'success)
                   (propertize "<nada>" 'face 'warning))
		 (if (transient-arg-value "--frobnicate" args)
                     "frobnification"
                   "froblessness")))))])
```

*Update*: I found a safer way and updated the above: just let-binding the `current-command` and `current-suffixes` to their matching internal variables.  This should be more robust against future changes to transient's internal data structures. 

*Update 2*: You cannot use `:command`, and using lambdas positionally doesn't work when the transient is _compiled_.  Using an external action command is fine.  See magit/transient#234.

**Comment by psionic-k** [comment]
Scope is an independent concept.  What was shown in the expression `(oref transient--prefix scope)` is that `transient--prefix` is an object (EIEIO) and you can access its slots, one of which is `scope`.

> my suffix description indeed updates on each key press.

Thanks.  I'll have to look into the behavior more.  Leaving this issue open.

**Comment by jdtsmith** [comment]
Right... just not sure what the use-case for scope is.  

BTW, the above example prefix had an issue related to `:command`, which isn't allowed.  As far as I can tell, you must use an external command symbol, not a lambda, in order to use a lambda description in a suffix.  See magit/transient#234.

**Comment by psionic-k** [comment]
Think of scope like a variable that you pass into the transient.  When manually invoking a transient with `(transient-setup NAME nil nil PARAMS)` the PARAMS argument is the scope and gets set on the prefix object, so it's slightly persistent.

You may be thinking, why not just pass the value into the transient's argument list or set the arguments in the interactive form?  When you think of the flow control complexity such as re-entering a parent transient, it makes sense that scope is attached to the prefix object instead of retained somewhere to be passed into the function again.

**Comment by psionic-k** [comment]
Is this issue safe to close?  I think it's already in the search index.  I feel like my latest explanation for scope is probably better than what's in the document.
